// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_kron_diag_kronT
arma::mat fast_kron_diag_kronT(const arma::mat& X, const arma::mat& A, const arma::vec& w);
RcppExport SEXP _BaMMI_fast_kron_diag_kronT(SEXP XSEXP, SEXP ASEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_kron_diag_kronT(X, A, w));
    return rcpp_result_gen;
END_RCPP
}
// kron_function
arma::mat kron_function(arma::mat A, arma::mat B);
RcppExport SEXP _BaMMI_kron_function(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(kron_function(A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BaMMI_fast_kron_diag_kronT", (DL_FUNC) &_BaMMI_fast_kron_diag_kronT, 3},
    {"_BaMMI_kron_function", (DL_FUNC) &_BaMMI_kron_function, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BaMMI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
